version: '2'
services:
  etcd:
    image: bitnami/etcd:latest
    ports:
      - "2379:2379"
    environment:
      ALLOW_NONE_AUTHENTICATION: "yes"
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    depends_on: [ zookeeper ]
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 172.31.8.141
      KAFKA_CREATE_TOPICS: "test:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181