apiVersion: v1
kind: ConfigMap
metadata:
  name: config.yaml
  annotations:
    flipped-aurora/gin-vue-admin: backend
    github: "https://github.com/flipped-aurora/gin-vue-admin.git"
    app.kubernetes.io/version: 0.0.1
  labels:
    app: gva-server
    version: gva-vue3
data:
  config.yaml: |
    Kafka:
      Address: 192.168.8.115:9092

    Etcd:
      Title: text
      Address: 127.0.0.1:2379

    SystemConfig:
      MaxKafkaBuffer: 10000
      MaxWatchBuffer: 1000
      MaxSentinel: 10

    EsConfig:
      Address: http://127.0.0.1:9200


    Zap:
      level: 'info'
      format: 'console'
      prefix: '[agent]'
      director: 'logs'
      link-name: 'latest_log'
      show-line: true
      encode-level: 'LowercaseColorLevelEncoder'
      stacktrace-key: 'disableStacktrace'
      log-in-console: true